# Generated by Django 4.2.5 on 2023-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extraction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="requirements",
            field=models.FileField(blank=True, null=True, upload_to="documents/json/"),
        ),
    ]
