name: deploy with ovh
on:
  push:
    branches:
      - main  # Déclencher le workflow lorsqu'un push est effectué sur la branche "main"

jobs:
  befor-deploy:
    name: Befor deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.OVH_IP_ADDRESS }}
          username: ${{ secrets.OVH_USER }}
          key: ${{ secrets.OVH_PRIVATE_KEY }}
          port: 22
          source: "./nginx, docker-compose.prod.yml"
          target: "/home/ubuntu/myriam/"

  deploy:
    runs-on: ubuntu-latest  # Utilisez l'image Ubuntu par défaut
    needs: befor-deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OVH_IP_ADDRESS }}
          username: ${{ secrets.OVH_USER }}
          key: ${{ secrets.OVH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/myriam/
            docker-compose -f docker-compose.prod.yml up -d --build